name: ST-Region
main: net.starly.region.RegionMain
author: Starly Team
website: https://discord.gg/TF8jqSJjCG

version: 1.1
api-version: 1.16

softdepend:
  - ST-Core

commands:
  stregion:
    aliases: [ strg, srg, 구역 ]