name: ST-Region
main: net.starly.region.RegionMain
author: Starly Team
website: http://starly.kr/discord

version: 1.1.4
api-version: 1.13

softdepend:
  - ST-Core

commands:
  stregion:
    aliases: [ strg, srg, 구역 ]