name: ST-Region
main: net.starly.region.RegionMain
author: Starly Team
website: https://discord.gg/TF8jqSJjCG

version: 1.0
api-version: 1.16

softdepend:
  - ST-Core

commands:
  region:
    aliases: [ 구역 ]